version: "3"

services:
  nugetserver:
    image: "nugetserver:latest"
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "5000:80"
    volumes:
      - //d/projetos/Services/NugetApi/NugetServer/wwwroot/packages:/app/wwwroot/packages/